### ISSUE TITLE
OH and AH collab dev: Login Image

### ISSUE THREAD

**Issue by OliveHamm14** [AlphaAndTheOshea/Parking-App-UNA#21]
![image](https://user-images.githubusercontent.com/66586011/114104284-306b8f00-9890-11eb-8c98-85d23d76cdf0.png)

**Comment by OliveHamm14** [comment]
For this collab, Alec and I created and coded the image into the Login page on Code Pen. My contributions for this collaboration was creating this custom image in Procreate on my iPad. I made sure I had the correct size canvas to work in the app and then I proceeded to sketch out the drawing. Procreate is similar to photoshop; I manipulated the layers to get this desired outcome for the graphic design. I then exported the file as a JPG so Alec could utilize it for our project.

**Comment by AlphaAndTheOshea** [comment]
My contribution to this collab is designing the login page, and implementing Olivia's MARVELOUS drawing into the design. I salvaged the code from one of my past projects, and it was a Lowe's themed login...... SO Olivia also helped me in find the hex codes for the colors involved in the login page. 

I also implemented a wee bit of js, so I had to brush up on it a bit. It was a Fun issue to work on!

**Comment by AlphaAndTheOshea** [comment]
See #20 for code, and HOPEFULLY Kaylin's Review......

**Comment by AlphaAndTheOshea** [comment]
As requested, Here is a [link to codepen!](https://codepen.io/alphaandtheoshea/pen/ZZPjXG)
And here is a link to the heroku deployment of my issue #20 branch! [https://parking-app-test202.herokuapp.com/](https://parking-app-test202.herokuapp.com/)
